import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from 'react-hot-toast'

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Provider from "./queryClient";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Provider>
          
        <GoogleOAuthProvider clientId="643858619832-o2u4ibcj1hl4fj7iv1kispp8o6mbv5ee.apps.googleusercontent.com">
     
         {children}
          </GoogleOAuthProvider>
          <ReactQueryDevtools/> 
          </Provider>        
      </body>
      <Toaster/>
    </html>
  );
}
